version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.fe
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/frontend

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.be
    ports:
      - "8080:8080"